sudo: false
language: go
go:
- '1.8'
- master
install:
- go get github.com/laher/goxc
script: make test build_release VERSION=$TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: CQcOuzCYYCDHrMurMwrddSZ4bSEEGA/Nuj7n1Fa01IE94Xce2WWAwjM0Yr7Of88bVmfDMXCXNo/A5THzKBv2ZO08xMjCk+ZVhgH03IK85S5KN7C6IwUZ9Bku1BRmFJwKKVvPLA0t3mT1dmOBiwIT3FUR2HfH9l8TjKiez3COnwt56qrnpnn8UegnM8yffvm4oCkRfzElb8mdErwOS1Ism7wljAL41oKmui5WWylbQFBsahKX7Gp8QKmPsrk0N4qikx3MuMA7OaLFT8U5R53UQynwjL/Jv1t3Zob0l40ZiLLjnE1D3ipuk/6mfgC+qnAGP8faoW2OD2Ab64rFdUQXvrWQbB6Cm2ruixfDSC6BPR3Imj7OUcZ3qF/H+DZuxGXLLgUPenlCkaErWI+riEsMJbNQR4f9/xWcx18JjfhB+dY75Ycpk5l+S7dXLPcfbjh6/wVE9Tv9mHnuR1aJHvhCoKNAATJ7swRK+ztc10eotWDPvjvzRqY4wHMCgxiIllkA8ny99UBexXNI0pZhQnWoYdB92OWe77I6vOb2LJ02Z+1Cl9/MVnvzz0F6LqqR4AwqGRMihHLTGKrCC+u6cqz8IMGu+34I5+/MtUIyliKvRaiz1ZCRefoGEcF0+TQUZU1+CbaZjWuZ+etBKQhWLq5JW5lMZNsaz8VPCbrST7e1J1M=
  file:
    - build/${TRAVIS_TAG}/forge_${TRAVIS_TAG}-darwin_amd64.zip
    - build/${TRAVIS_TAG}/forge_${TRAVIS_TAG}-linux_amd64.zip
    - build/${TRAVIS_TAG}/forge_${TRAVIS_TAG}-windows_amd64.zip
  on:
    tags: true
